{
 "title": "Node Express App",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_version_info" }
   ]
  },
  {
   "title": "Up (can get metrics)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Scrape Duration (Seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  },
  {
   "title": "Process Heap Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_heap_bytes" }
   ]
  },
  {
   "title": "response time summary SLIDING quartiles",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "response_time_summary_sliding" }
   ]
  },
  {
   "title": "response time summary quartiles",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "response_time_summary" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "response_time_summary" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "response_time_summary" }
   ]
  }
 ]
}